config/routes.rb
Rails.application.routes.draw do
  get 'kittens/index'
  get 'kittens/show'
  get 'kittens/new'
  get 'kittens/create'
  get 'kittens/edit'
  get 'kittens/update'
  get 'kittens/delete'
  root to: 'kittens#index'
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: 'Kitten created'
    else
      render :new, status: :unprocessable_entity, alert: 'Kitten not created'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: 'Kitten updated'
    else
      render :edit, status: :unprocessable_entity, alert: 'Kitten not updated'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, notice: 'Kitten destroyed :('
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  <div>
    <%= f.label :cuteness %>
    <%= f.select :cuteness, options_for_select((1..10).step(1).collect { |i| [i, i] } ) %>
  </div>
  <div>
    <%= f.label :softness %>
    <%= f.select :softness, options_for_select((1..10).step(1).collect { |i| [i, i] } ) %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/delete.html.erb
<h1>Kittens#delete</h1>
<p>Find me in app/views/kittens/delete.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<%= render 'form', kitten: @kitten %>
<div>
    <%= link_to 'Delete', kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </div>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
    </li>
    <div>
    <%= link_to 'Delete', kitten_path(kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </div>
  <% end %>
</ul>
<div>
  <%= link_to 'Add a kitten!', new_kitten_path %>
</div>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<h1> <%= @kitten.name %> </h1>
<div>
  <div>Age: 
    <%= @kitten.age %>
  </div>
  <div> Cuteness: 
    <%= @kitten.cuteness %>
  </div>
  <div> Softness: 
    <%= @kitten.softness %>
  </div>
  <div>
    <%= link_to 'Edit', edit_kitten_path(@kitten) %>
  </div>
  <div>
    <%= link_to 'Delete', kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </div>
</div>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>